Add config dropDownCollapsable
tejuamirthi/CustomDropDown pull request #25
Opened 2020-10-25 16:26 UTC by devanshimodha

# Description

Add dropDownCollapsable in DropDownConfig

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)\
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe on what device it is tested

* Xcode: Version 12.0.1 
* Model name: iPhone SE (2nd Generation) - iOS 13.5

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# Reviewers:

Please tag relevant people requesting a review

2020-10-25 16:51 UTC, tejuamirthi requested changes

2020-10-25 16:51 UTC, tejuamirthi commented on Example/ViewController.swift
> +    func config(identifier: Int) -> DropDownConfig {
As the default value is true for dropDownCollapsable, we dont need this block of code. Remove this

2020-10-25 16:54 UTC, tejuamirthi commented
Hey @devanshimodha, as you are working on this issue, can you take a look at #17

2020-10-26 02:07 UTC, tejuamirthi approved these changes

2020-10-26 02:08 UTC, tejuamirthi commented
Dropdown collapsable option

2020-10-26 02:08 UTC, merged

2020-10-26 05:37 UTC, devanshimodha commented
Hello @tejuamirthi 

I am geetting this error in hacktoberfest portal

"Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR. "

2020-10-26 05:42 UTC, tejuamirthi commented
> Hello @tejuamirthi
> 
> I am geetting this error in hacktoberfest portal
> 
> "Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR. "

How about now? Is it showing the same?

2020-10-26 05:52 UTC, tejuamirthi commented
Hey @devanshimodha 
If you see the same again, please look at the other issues and contribute. Because this pr is merged, I guess it may not have a chance to validate.

2020-10-26 06:17 UTC, devanshimodha commented
Done, I'll try to solve other issues too