Cao issue 22
tejuamirthi/CustomDropDown pull request #37
Opened 2021-02-25 05:07 UTC by caocmai

# Description

I added the ability to change the background color of the dropdown list. I also added so whenever the dropdown list has an image then show that image along with the text in the selection view. 

Fixes # 11

## Type of change

Strictly added only UI changes. 

# How Has This Been Tested?

It has been tested on the iPhone 8 and iTouch 7 by the simulator was well as on my device. 

* Xcode: 12.4
* Model name:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# Reviewers:

Please tag relevant people requesting a review

2021-02-25 10:03 UTC, tejuamirthi requested changes
Thanks @caocmai for contributing! It looks good. Please make these above changes and re-request a review.

2021-02-25 10:03 UTC, tejuamirthi commented on CustomDropDown/View/DropDownDisplayView.swift
> +//        title.tag = tag
Please remove the code you've commented yourself, if that won't be used. Don't remove the old commented code though. Thanks

2021-02-25 10:03 UTC, tejuamirthi commented on Example/LabelStyleViewController.swift
> +        let ccp = CustomDropDownPresenter<String>(items: items, delegate: self, listColor: .cyan, selectedColor: .yellow)
Same as above. Please use a more reliable set of colors, so that user's can use from the example directly.

2021-03-01 16:51 UTC, caocmai commented
Hi, thanks for the thorough feedback, I think I fixed everything. Also I decided to move the selected and background color of the dropdown in the config area instead of the view. 

As regard to the colors, you can change it to whatever you think it's best I was just trying to show that it works, it's not important to me. 

Uploaded new changes and requested new review. Thanks

2021-03-04 17:28 UTC, tejuamirthi commented
Sorry for getting back late @caocmai

2021-03-04 17:28 UTC, tejuamirthi approved these changes
LGTM!

2021-03-04 17:30 UTC, merged

2021-03-04 17:38 UTC, tejuamirthi commented on CustomDropDown/View/DropDownDisplayView.swift
> +    }()
#38

2021-03-04 17:39 UTC, tejuamirthi commented on CustomDropDown/View/DropDownDisplayView.swift
> +    }()
Let me know @caocmai if you'd like to work on this issue too. Thanks!